### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by UnixCro** [dx4iot/insta-scraper#1]
```
home@macOS insta-scraper % python3 instainfo.py
Traceback (most recent call last):
  File "instainfo.py", line 3, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

home@macOS  insta-scraper % python3 -V; python -V 
Python 3.8.2
Python 2.7.16
```

**Comment by danwyryunq** [comment]
for you it doesn't work because you did not install the requirement as described in the readme. you should 
`pip install bs4 requests`

**Comment by UnixCro** [comment]
Thanks for your answer

`pip3 install --user bs4 requests`
`Successfully installed beautifulsoup4-4.9.3 bs4-0.0.1 soupsieve-2.2`


```
PRESS S TO START: S
Enter Username: myusername
```

```
Traceback (most recent call last):
  File "instainfo.py", line 119, in <module>
    instascrap()
  File "instainfo.py", line 60, in instascrap
    instaProfilePic = instaPP.get("content")
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by AniGoddie** [comment]
delete your existing repo `rm -rd (filename)` and again git clone this repo, I made some changes in the code
